### ISSUE TITLE
Add json translation

### ISSUE THREAD

**Issue by bcaro** [ktn001/traduitjdm#27]
my json files contain text to translate. It is possible to add json files in your search ?
Thank's

**Comment by ktn001** [comment]
Hello,
Oui, je vais regarder pour ajouter les fichier axant l'extension ".json".

Je ne vais probablement pas pouvoir le faire avant la semaine prochaine.

**Comment by ktn001** [comment]
Hello,
C'est implémenté dans la release 0.7.0
