### ISSUE TITLE
Purge des textes non utilisés

### ISSUE THREAD

**Issue by bcaro** [ktn001/traduitjdm#28]
Bonjour,
et toujours merci pour ce script très utile.
Ayant modifié mes textes à traduire, je les ai effacés du fichier xx_XX.json.
quand j'exécute le script, ils réapparaissent.
J'aimerai faire une purge  des anciens textes qui n'existent plus.

**Comment by ktn001** [comment]
Bomjour,
Je regarde ça dans la semaine et essaie de fournir une solution d'ici le 10 janvier.

**Comment by ktn001** [comment]
Hello,
Je ne comprends pas.

J'ai créé une ligne
```
$txt = __("Ceci est un test",__FILE__);
```
Dans un fichier php d'un plugin que je suis en train d'écrire, Ensuite, j'ai lancé la commande
```
traduitjdm -l en_US,fr_FR <mon_plugin>
```
Le nouveau texte a bien été ajouté dans les fichiers `en_US.json` et `fr_FR.json`.
J'ai ensuite supprimé la ligne ajoutée dans le fichier php et relancé la commande `traduitjdm -l en_US,fr_FR <mon_plugin>`.

Le texte était toujours dan les fichiers `en_US.json` et `fr_FR.json`.

J'ai alors supprimé le texte de test dans le fichiers `en_US.json` et `fr_FR.json` avant de relancer la commande `traduitjdm -l en_US,fr_FR <mon_plugin>` et constater que le texte n'y pas été remis dans les fichiers `json`.


Ceci dit, je pense ajouter une option de purge qui permettra d'indiquer que les textes qui sont dans les `json` mais plus dans le code devront être supprimés.

**Comment by ktn001** [comment]
J'ai trouvé :)

Le texte réapparais s'il n'a pas été retiré de TOUS les fichiers `json`.

Je vais travailler sur l'évolution qui inclura une option de purge.
