### ISSUE TITLE
__('texte',__FILE__) n'est pas traduit

### ISSUE THREAD

**Issue by bcaro** [ktn001/traduitjdm#29]
J'ai peut être mal compris ce passe :
Les textes traduits par la fonction __('texte',__FILE__) dans les scripts phpdoivent être encdrés par des quotes ou double quotes (' ou "). 

j'ai donc ceci dans mon code:

`
if (!isset($_FILES['file'])) {
			throw new Exception(__('texte',__FILE__));
		}
`
et ce n'est pas répercuté dans le fichier de traduction. Sur une version plus ancienne du script cela fonctionnait.

**Comment by ktn001** [comment]
Corrigé en 10.0.2
