### ISSUE TITLE
Verifier l'existence du dossier jeedomDir configuré

### ISSUE THREAD

**Issue by mguyard** [ktn001/traduitjdm#32]
Bonjour,

Dans le cas où le répertoire n'existe pas, l'erreur est :

`Traceback (most recent call last):
  File "./bin/traduitjdm", line 355, in <module>
    options()
  File "./bin/traduitjdm", line 205, in options
    if jeedomDir.endswith("/"):
AttributeError: 'bool' object has no attribute 'endswith'`

Il serait bien de tester l'existence du répertoire pour avoir une erreur plus compréhensible

**Comment by ktn001** [comment]
Le problème est au niveau du traitement de la config "jeedomDir" lors de la lecture du fichier de config.

**Comment by ktn001** [comment]
Le correctif est prêt. Il sera déployé en même temps que celui du bug #33

**Comment by ktn001** [comment]
Correctif déployé en version 1.0.4
