### ISSUE TITLE
Erreur quand "exclude" non configuré

### ISSUE THREAD

**Issue by mguyard** [ktn001/traduitjdm#33]
Hello,

Dans le cas où on utilise le fichier de configuration, si on laisse commenté toute la partie exclusion (pour laisser par défaut aucune exclusion), l'erreur suivant apparait :

```
Traceback (most recent call last):
  File "./bin/traduitjdm", line 357, in <module>
    get_textes_from_source()
  File "./bin/traduitjdm", line 258, in get_textes_from_source
    for d in excludes:
NameError: name 'excludes' is not defined
```

Si on active une exclusion, ca fonctionne

**Comment by ktn001** [comment]
Une variable globale était mal nomée

**Comment by ktn001** [comment]
Correctif déployé en version 1.0.4
